image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./s00_dev_init_env.sh
    command: ./s09_dev_run_local.sh
ports: 
  - port: 8000
    onOpen: open-preview
  - port: 8001
    onOpen: ignore
  - port: 8002
    onOpen: ignore
  - port: 8003
    onOpen: ignore
  - port: 8004
    onOpen: ignore
  # dynamodb
  - port: 8100
    onOpen: ignore
  # unittest
  - port: 8200
    onOpen: ignore
