#!/bin/bash -e

PROJECT_ROOT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

LOCAL_STAGE=local
LOCAL_DYNAMODB_PORT=8100
LOCAL_PUBLIC_COMPUTE_PORT=8000
LOCAL_PUBLIC_STATIC_PORT=8001
LOCAL_PUBLIC_DEPLOYGEN_PORT=8002
LOCAL_PUBLIC_MUTABLE_PORT=8003
LOCAL_PUBLIC_TMP_PORT=8004
LOCAL_CONF_PATH=${PROJECT_ROOT_PATH}/stages/${LOCAL_STAGE}
LOCAL_VAR_DIR_PATH=${PROJECT_ROOT_PATH}/dev_env/var
LOCAL_TMP_DIR_PATH=${PROJECT_ROOT_PATH}/dev_env/tmp
LOCAL_DYNAMODB_TABLE_NAME=tmp_table
LOCAL_DYNAMODB_REGION=`jq -r  .AWS_REGION ${LOCAL_CONF_PATH}/conf.json`
LOCAL_DYNAMODB_ENDPOINT_URL="http://localhost:${LOCAL_DYNAMODB_PORT}"
LOCAL_AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXXX
LOCAL_AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# fuck gitpod
unset PIPENV_VENV_IN_PROJECT
unset PIP_USER
unset PYTHONUSERBASE

kill_pid() {
  if [ -f "$1" ];then
    kill `cat $1` || true
    rm -f "$1"
  fi
}
